on:
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Build
          run: |
            gzip -n < r.txt > r.gz
            gh release upload ${{github.event.release.tag_name}} r.gz
          env:
            GITHUB_TOKEN: ${{ github.TOKEN }}
          shell: bash
