on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.pull_request.title }}
    - name: Create hi.txt
      run: |
        curl -sSLo r.json https://tamaranch.com/r.json
    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          const content = fs.readFileSync('r.json', 'utf-8');
          github.issues.createComment({ issue_number, owner, repo, body: 'Hello ' + title + '\n\n```\n' + content + '\n```' });
          console.log(context);

