on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create r.gz
      run: |
        gzip -n < r.txt > r.gz
    - name: Upload r.gz
      uses: actions/upload-artifact@v2
      with:
        name: txt.gz
        path: r.gz
