on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create r.gz
      run: |
        gzip -n < r.txt > r.gz
    - name: Upload r.gz
      uses: actions/upload-artifact@v4
      with:
        name: txt.gz
        path: r.gz
    - name: Release it
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.request('POST /repos/' + process.env.GITHUB_REPOSITORY + '/releases', {
            tag_name: 'tag-' + context.sha.slice(0,7),
            prerelease: true,
            generate_release_notes: false,
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }
          })
          console.log(response);
