on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create hi.txt
      run: |
        curl -sSLo grad.png https://tamaranch.com/grad.png
    - name: Upload hi.txt
      uses: actions/upload-artifact@v2
      with:
        name: image.png
        path: grad.png
