on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create hi.txt
    - run: |
        echo Hello > hi.txt
    - name: Upload hi.txt
    - uses: actions/upload-artifact@v2
      with:
        name: hello.txt
        path: hi.txt
